export const NavRoutes = {
  HOME: "Home",
  INTERNSHIP: "Certificate Internship",
  ABOUT_US: "About us",
  WORKSHOP: "Workshop",
  LOGO_URL: "Image",
  SERVICES: "Services",
  BLOGS: "Blogs",
  CONTACT_US: "Contact us",
  TRAINING: "Course & Training",
  HIGH_SCHOOL: "School & High School",
  UNIVERSITY: "University",
  CUSTOM_DRONES: "Custom Drones",
  DESIGN: "Design & Fabrication",
  PROJ_CONSULT: "Project Consultation",
  CFD_ANALYSIS: "Structure & CFD Analysis",
  PRINTING_SERVICES: "",
  CreateBlogs: "CreateBlogs",
  EditBlogs: "EditBlogs"
} as const;
